### ISSUE TITLE
i put qb-inventory top still geting this message

### ISSUE THREAD

**Issue by primoixi** [swkeep/keep-bags#19]
i am getting  this  1: `qb-inventory` must started before `keep-harmony`   what should i do? is it ok to continue ignoring?

**Comment by swkeep** [comment]
No, as the error stated, you need to fix the loading order

```text
ensure qb-core
ensure illenium-appearance
ensure [qb]
ensure [standalone]
ensure [voice]
ensure [defaultmaps]
ensure keep-harmony
# other scripts
ensure keep-bags
```

**Comment by primoixi** [comment]
ok thanks for the information
