### ISSUE TITLE
ox _inventory bag wont open

### ISSUE THREAD

**Issue by DatBoiRoasta** [swkeep/keep-bags#24]
and states that bag is open already
![image](https://github.com/swkeep/keep-bags/assets/113279020/79dd2663-eb6d-498c-be10-ba9a1e0232ef)

**Comment by spero33** [comment]
same issue after i open a bag. but with QB inventory.

**Comment by konrad50024** [comment]
Having same issue, there is something up with the code when it registers a stash, works once you relog but when you first get a bag just has that issue
